//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerBootsBN
{
    using System;
    using System.Collections.Generic;
    
    public partial class BootCart
    {
        public int ID { get; set; }
        public string CustomerID { get; set; }
        public int ProductID { get; set; }
        public int Price { get; set; }
        public Nullable<System.DateTime> DateBought { get; set; }
        public bool InsideCart { get; set; }
    
        public virtual BootProduct BootProduct { get; set; }
    }
}
