//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerBootsBN
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1525596_co5027Entities : DbContext
    {
        public db_1525596_co5027Entities()
            : base("name=db_1525596_co5027Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BootCart> BootCarts { get; set; }
        public virtual DbSet<BootProduct> BootProducts { get; set; }
        public virtual DbSet<BootType> BootTypes { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
    }
}
